tags:
- name: api
  description: URRL API

paths:
# [GET] /api/shorturl/analytics
  /api/shorturl/analytics:
    get:
      tags:
      - api
      summary: Get all URRLs analytics information
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] /api/shorturl
  /api/shorturl:
    post:
      tags:
      - api
      summary: Create a URRL from an original URL
      parameters:
      - name: body
        in: body
        description: URL 
        required: true
        schema:
          $ref: '#/definitions/url'
      responses:
        200:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

# [GET] /api/shorturl/:hash
  /api/shorturl/{hash}:
    get:
      tags:
      - api
      summary: Retrieve an original URL from a Hash
      parameters:
      - name: hash
        in: path
        description: Hash Id
        required: true
        type: string
      responses:
        301:
          description: 'Redirect'
        500:
          description: 'Server Error'

# definitions
definitions:
  url:
    type: object
    required:
        - url
    properties:
      url:
        type: string
        description: URL to create URRL from

schemes:
 - http
